### ISSUE TITLE
ncm2 is slow on iTerm2

### ISSUE THREAD

**Issue by iamcco** [ncm2/ncm2#7] opened 2018-07-07 13:25 UTC
ncm:
![2018-07-07 21_20_46](https://user-images.githubusercontent.com/5492542/42411290-e74f360a-822b-11e8-9d84-c3947bb0f8c4.gif)

ncm2:
![2018-07-07 21_18_12](https://user-images.githubusercontent.com/5492542/42411301-1c2c9782-822c-11e8-9521-df74c417ef70.gif)

**Comment by roxma** [comment] 2018-07-07 14:06
I need minimal vimrc, nvim version, os environment for reproducing the behavior

**Comment by iamcco** [comment] 2018-07-07 14:29
os: macOS version: 10.13.3
nvim version:
```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
```

minimal vimrc:
```
scriptencoding utf-8

call plug#begin(expand('<sfile>:p:h') . '/plugged')
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
call plug#end()

set completeopt=noinsert,menuone,noselect
autocmd BufEnter * call ncm2#enable_for_buffer()
inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

nvim check:
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: pyenv was found, but $PYENV_ROOT is not set. `pyenv root` will be used. If you run into problems, try setting $PYENV_ROOT explicitly.
  - INFO: pyenv: /usr/local/Cellar/pyenv/1.2.2/libexec/pyenv
  - INFO: pyenv root: /Users/aioiyuuko/.pyenv
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /Users/aioiyuuko/.pyenv/versions/2.7.12/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: pyenv was found, but $PYENV_ROOT is not set. `pyenv root` will be used. If you run into problems, try setting $PYENV_ROOT explicitly.
  - INFO: pyenv: /usr/local/Cellar/pyenv/1.2.2/libexec/pyenv
  - INFO: pyenv root: /Users/aioiyuuko/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /Users/aioiyuuko/.pyenv/versions/3.6.4/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v9.8.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

```

**Comment by iamcco** [comment] 2018-07-07 14:43
![image](https://user-images.githubusercontent.com/5492542/42411863-62d9c92a-8236-11e8-8605-d24e36174e90.png)

the char `l` from hidden to show

**Comment by roxma** [comment] 2018-07-07 14:59
hmm....
Unfortunately I cannot reproduce ... Maybe it's mac related.

**Comment by lgy87** [comment] 2018-07-07 15:36
same here.

macOS version: 10.13.3
nvim version: NVIM v0.3.1-120-g1248178

**Comment by roxma** [comment] 2018-07-07 15:47
What's the CPU usage of nvim when the typing gets really slow?

You could try tweak the `autoload/ncm2.vim`, try make some changes, and see whether the issue still exists.


### Attempt 1:
Try remove the `TextChangedI` in line 60.

 `b:changedtick` used to be buggy in vim/neovim.

### Attempt 2

Perhaps the complete call is time comsuming. Try modify line 238
```
    call complete(s:startbcol, s:matches)
```
into
```
     if !pumvisible() && empty(s:matches)
        return
    endif
    call complete(s:startbcol, s:matches)
```

**Comment by iamcco** [comment] 2018-07-07 16:07
> Try remove the TextChangedI in line 60.

it's works well when typing

> Attempt 2

when do this 100% CPU usage

**Comment by roxma** [comment] 2018-07-07 17:19
`TextChangedI` is now removed due to this issue.

Let's keep the issue open, before the underlying vim/neovim issue is confirmed.

**Comment by iamcco** [comment] 2018-07-08 01:36
> > Try remove the TextChangedI in line 60.
> 
> it's works well when typing

it seems that it's also a little bit slow then ncm when i switch back to ncm.

also, the mac Terminal.app seems more well then iTerm2.app. Maybe iTerm2.app is too slow.

**Comment by roxma** [comment] 2018-07-08 07:44
@iamcco 

It's not the issue of terinal emulator.

100 % CPU suggests that something is being infinitely triggered by some combination of autocmd and key mapping. It's probably `TextChangedI` in this case.

**Comment by iamcco** [comment] 2018-07-08 08:30
The 100% CPU usage is happen that when i change 



call complete(s:startbcol, s:matches)



to



  if !pumvisible() && empty(s:matches)
        return
  endif
  call complete(s:startbcol, s:matches)



it doesn't occur before i do this change and the iTerm2.app is slow down more than the Terminal.app. Maybe iTerm2 is real slow

**Comment by roxma** [comment] 2018-07-09 02:04
@iamcco 

That's wired, the change shouldn't have effect like that

Do you mean that the 100% CPU issue  doesn't exist even when `TextChangedI` is re-added?

**Comment by iamcco** [comment] 2018-07-09 02:17
@roxma  yes

**Comment by roxma** [comment] 2018-07-09 03:08
hmm... but somehow removing  `TextChangedI` avoids the issue.

**Comment by roxma** [comment] 2018-07-09 03:42
Pleast test the latest commit

**Comment by lgy87** [comment] 2018-07-09 10:40
@roxma 
my issue: **be the same with @iamcco**:

when i change like this, the cpu will raise to 100%

<img width="374" alt="a" src="https://user-images.githubusercontent.com/17808424/42445559-0d217ad4-83a6-11e8-9654-d6f373999c10.png">

and after i removed `TextChangedI`, it's faster.

---------------

after your updating: now i use `fbbd9f6` commit:
it is slow all the same.
so i removed `TextChangedI`

But, i found that it's as fast as i hope if I go into `:terminal` mode, which cursor is `block`.

**Comment by roxma** [comment] 2018-07-09 11:08
Oh, it's my mistake, 

```vim
     if !pumvisible() && empty(s:matches)
        return
    endif
```
should be written as

```vim
     if !pumvisible() && empty(s:matches)
        return ''
    endif
```

**Comment by roxma** [comment] 2018-07-09 11:38
Due to #10, empty matches check is also pushed to the master, please test again.

**Comment by lgy87** [comment] 2018-07-09 12:34
@roxma thanks for your rapid reply.

<img width="539" alt="x" src="https://user-images.githubusercontent.com/17808424/42450339-60c51a96-83b6-11e8-9778-fbc659cc5546.png">

when i typing, cpu is raises to 50%+, 

<img width="702" alt="b" src="https://user-images.githubusercontent.com/17808424/42450629-6770b7a0-83b7-11e8-9949-23b5fb7144d6.png">

when i stop typing: 
<img width="512" alt="c" src="https://user-images.githubusercontent.com/17808424/42450357-6dc37062-83b6-11e8-9382-ace0ed1fce4b.png">

**Comment by iamcco** [comment] 2018-07-09 16:24
test the latest commit.

neovim in iTerm2.app:

1. i can feel it slow down the cursor when typing
2. if type the key very fast the python process cpu will raise to 99% and will block the cursor.

![2018-07-10 00_20_00](https://user-images.githubusercontent.com/5492542/42462957-5be2b166-83d7-11e8-8f5d-b47695632563.gif)
 
neovim in Terminal.app:

1. it's faster
2. if type the key very fast the python process cpu will raise to 99% but i can still type very fast and it will not block the cursor. 

![2018-07-10 00_22_16](https://user-images.githubusercontent.com/5492542/42462981-6ecc561a-83d7-11e8-8489-1a1072288483.gif)

**Comment by roxma** [comment] 2018-07-09 16:55
Thanks for the information. I think we should conclude that this is iTerm2 issue.

-------------------------
By the way,

> if type the key very fast the python process cpu will raise to 99%

In current implementation, the python part processes every notification sent from neovim. It's possible that the python is too slow to consuming the messages.

Add some kind of queing and invalidating method might help. But the implementation will become more complicated, and even more messy considering neovim python client's concurrent greenlet behavior. I don't see the need for adding this feature at this point. But probably we'll get there in the future.

**Comment by roxma** [comment] 2018-07-09 17:06
Perhaps `set lazyredraw` could speedup the rendering?

**Comment by lgy87** [comment] 2018-07-10 01:42
maybe it's iterm2's issue.

in terminal.app typing is smooth.

**Comment by lgy87** [comment] 2018-07-10 01:57
@iamcco , can you test Iterm2 with `nvim -U NONE`

i open nvim with no config loaded, it is fast, too.

i am confused. maybe it's iterm2 and neovim 's issue.

:(

**Comment by lgy87** [comment] 2018-07-10 02:06
`https://iterm2.com/downloads.html`

@iamcco please use iterm2(version: 3.1.7), which is a stable Release.

in my case, the cpu and cursor are all ok.

please test it and give a response. thanks.

-------------

@roxma, thank you for your good job. 👍 
@iamcco thanks for the testing. 👍

**Comment by iamcco** [comment] 2018-07-10 03:21
@roxma @lgy87 
test with iTerm2 v3.1.7 it works well, thanks.

**Comment by cvincent** [comment] 2018-07-10 17:05
One thing that *might* help is to enable GPU rendering under iTerm2's experimental features. `Preferences > Advanced > Use Metal GPU-based renderer`. You may need to update iTerm2 if you don't see it. If you use translucent backgrounds, they will become opaque, but it's a small price to pay. I enabled this feature last week and absolutely everything in NeoVim (and just in general) is way faster, including autocompletion.

**Comment by iamcco** [comment] 2018-07-11 11:50
@cvincent i use the iTerm2 (Build 3.2.0beta6), it's slow but v3.1.7 is faster

**Comment by lgy87** [comment] 2018-07-12 01:39
@iamcco @cvincent 
There is **not** GPU rendering in iTerm2 beta. maybe it's the reason.

**Comment by svanharmelen** [comment] 2018-09-26 10:35
Any updates on this issue, I'm seeing the exact same lag when typing and using `ncm2` with iTerm2 (latest beta)?

**Comment by lgy87** [comment] 2018-10-03 05:33
@svanharmelen 
Please use the stable version. i guess it's the issue of iterm2.

**Comment by roxma** [comment] 2018-12-07 05:40
Does this issue still persist with the latest version?

**Comment by iamcco** [comment] 2018-12-07 06:09
@roxma i have updated ncm2 and test on Iterm2 (Build 3.2.6) with neovim v0.3.2-dev , it works well for me.

**Comment by roxma** [comment] 2018-12-07 06:19
I'm not sure what's the root cause. It's probably a side effect of `feedkeys`. `feedkeys` has been remove in the latest version.

Closing this issue since it does not exist anymore.

**Closed by roxma** 2018-12-07 06:19 UTC
Labels: cannot-reproduce, help wanted
