### ISSUE TITLE
Floating window support?

### ISSUE THREAD

**Issue by alok** [ncm2/ncm2#147] opened 2019-03-06 21:17 UTC
Neovim recently added support for floating windows. I noticed coc.nvim uses it, and I was wondering if there were any plans for it in ncm2.

**Comment by roxma** [comment] 2019-03-07 02:51
This is what we have with current nvim master so far: https://github.com/ncm2/float-preview.nvim

With https://github.com/neovim/neovim/pull/9616 plugin could draw the floating window near to the popup menu. Though ideally I think this kind of feature should be builtin for neovim, which requires volunteer(s).

**Comment by roxma** [comment] 2019-03-07 04:26
See also: https://github.com/neovim/neovim/issues/9663

> there could be a global option that configures the "preview window"

**Comment by roxma** [comment] 2019-03-17 10:46
Since  neovim/neovim#9616 is merged, I have added floating support in https://github.com/ncm2/float-preview.nvim

It's still kind of rough edges. With floating window I think we should probably remove the `menu` field of the completion items.

**Comment by Shougo** [comment] 2019-03-18 03:43
I have tested the plugin.  It works but it seems slow for me.

**Comment by roxma** [comment] 2019-03-18 11:47
>  It works but it seems slow for me.

I'm not sure what's the root cause. I don't this issue on my PCs.

I have probably improved the cache behavior at  https://github.com/ncm2/float-preview.nvim/commit/0335e7c7b30bad3d5082bd8bf9c09ac41d7583a7.

**Comment by Shougo** [comment] 2019-03-18 11:49
Thanks.  I will try it later

**Comment by Shougo** [comment] 2019-03-18 14:53
I have tested it,  it is better performance.  Thanks!

**Comment by butterflyfish** [comment] 2019-06-17 09:19
i try  ncm2/float-preview.nvim w/ nightly build neovim(v0.4.0-1046-gd32b92e26), but i can not see floating window. file is golang. is there any other special settings ?

**Comment by roxma** [comment] 2019-06-17 09:41
@butterflyfish float-preview.nvim applies to `:help complete-items` with `info` field available.

You could check the item by `:echo v:completed_item`  after completion.

**Comment by butterflyfish** [comment] 2019-06-17 10:09
@roxma, *info* field is empty. I use **go-langserver** w/ **LanguageClient-neovim**. which provide *info* field ?

**Comment by roxma** [comment] 2019-06-17 10:26
@butterflyfish 

See [LangaugeClient-neovim type.rs:549](https://github.com/autozimu/LanguageClient-neovim/blob/3e31d01da54aaad3905da813cf7d3564bc8d98d7/src/types.rs#L549)

go-langserver is responsible for providing `lspitem.documentation`, which is defined in [lsp-spec](https://github.com/microsoft/language-server-protocol/blob/800c75b1ce901845b33f739f4331c324b1b96f75/specification.md#completion-request-leftwards_arrow_with_hook)


LCN convert `documentation` into `info` for vim.

You could [enable logging](https://github.com/autozimu/LanguageClient-neovim/blob/3e31d01da54aaad3905da813cf7d3564bc8d98d7/doc/LanguageClient.txt#L222) to inspect the LSP traffic to prove that go-langserver is not providing `documentation`

**Comment by butterflyfish** [comment] 2019-06-18 06:51
after enable logging, *info* field is still empty. maybe go-langserver does not support. hover works well. i had upgrade go-langserver to latest version.

**Comment by butterflyfish** [comment] 2019-06-20 01:45
@roxma , is there any special neovim setting ? I switch to gopls, it still has no floating window to show doc/info. but hover work well by floating window. BTW, I upgraded LanguageClient-neovim repository to June/19(commit id: 8356cbe0939dcfe7010087cfba887bc2edaeebd4).

**Comment by roxma** [comment] 2019-06-20 13:38
@butterflyfish

If there's no `documentation` from LSP server, it's LSP server issue.

As mentioned before, use the logging to prove it.

**Comment by butterflyfish** [comment] 2019-06-21 01:36
I saw it using Python Language Server. thank you! great job!

**Closed** 2019-07-03 08:04 UTC
Labels: enhancement
