### ISSUE TITLE
not work for Neovim under windows 10

### ISSUE THREAD

**Issue by anson2416** [ncm2/ncm2#103] opened 2018-11-25 18:14 UTC
If you're having trouble with NCM2, Please provide the following information
along with your detailed issue description:

### OS

windowns 10 64bit

### neovim `:version` output
 NVIM 0.3.1 

### Minimal vimrc for reproducing the issue
```sh
" using **vim-plug**
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-jedi'

" enable ncm2 for all buffers
"autocmd BufEnter * call ncm2#enable_for_buffer()
" **i have to comment the above  line, otherwise nvim can't start up**

set completeopt=noinsert,menuone,noselect
```

### neovim `:messages` output when the error occurs
Nil

### Log files if you think the issue is a bug

no idea how to create the log in windows.

```sh
export NVIM_PYTHON_LOG_FILE=/tmp/log
export NVIM_PYTHON_LOG_LEVEL=DEBUG
nvim
# reproduce the issue
```

**Comment by roxma** [comment] 2018-12-06 11:39
![peek 2018-12-06 19-38](https://user-images.githubusercontent.com/4538941/49581980-9b3df000-f98e-11e8-9f0c-05d1ed9841c4.gif)

Cannot reproduce. Closing...

**Closed by roxma** 2018-12-06 11:39 UTC
